### ISSUE TITLE
Feature: Support port mappings

### ISSUE THREAD

**Issue by SBSTP** [SBSTP/rust-igd#1]
[Spec](http://upnp.org/specs/gw/UPnP-gw-WANIPConnection-v1-Service.pdf), `AddPortMapping` & `DeletePortMapping`

**Comment by vinipsmaker** [comment]
[One very popular UPnP stack on Linux based devices is Linux IGD](http://linux-igd.sourceforge.net/). This stack has a few quirks and one worth mentioning is the fact that [it'll reject port mapping requests which don't include a `NewPortMappingDescription`](http://www.upnp-hacks.org/stacks/linuxigd.html). It may be worth to support the `NewPortMappingDescription` attribute and encourage its use in the documentation.

**Comment by vinipsmaker** [comment]
Bump version now that new API was added? Or will you wait til conversion from non-member functions to member-functions? Should I do the conversion or will you do?

**Comment by SBSTP** [comment]
I can bump now, yes. I'm re-organizing the code base so it might take a while. I'll rebump later.
