### ISSUE TITLE
Future/Tokio compatible

### ISSUE THREAD

**Issue by maufl** [sbstp/rust-igd#30]
Is there a futures aware and tokio compatible version planned?

**Comment by sbstp** [comment]
Not right now. tokio is being reworked, so I would wait for that before attempting to write it. You can also run this library in a thread pool, giving you the same result. If you want to take a shot at it, I'll review and merge it though.

**Comment by maufl** [comment]
I would probably able to do it. Do you think there should then be always two methods? One that returns a Future but does not block and one that does block? Or should there only be a Future version and a user would call wait to block?

**Comment by sbstp** [comment]
I wouldn't change the current API. I would also add the tokio support behind a feature flag, so that you can only enable it when you need it. So it would be a separate async API.

**Comment by maufl** [comment]
Hm, hyper works either with or without tokio but not both. Would it be ok if tokio was always used but a synchronous API was still provided?

**Comment by sbstp** [comment]
No way to avoid it I guess. A lot of people are using the current API, so let's no break it. Just add the async support as a new API.

**Comment by maufl** [comment]
I updated the implementation to adjust for changes in tokio/hyper. 
https://github.com/maufl/rust-igd/tree/update-hyper
I'm not sure whether the implementation should be merged, I think the error handling could be improved.
